server:
  port: ${SERVER_PORT:8888}
  servlet: # sửa lỗi font tiếng việt
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  servlet:
#    context-path: /api
#  tomcat:
#    threads:
#      max: 100
#      min-spare: 50
#    accept-count: 20000
spring:
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  messages: # Cấu hình message chuận utf8 tránh lỗi font tiếng việt
    encoding: UTF-8
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:roomx}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    dbcp2: # Các connection qua pool mặc định  sẽ đi vào đây
    #      default-schema: ${DB_SCHEMA_DBCP2:schema_roomx}
    hikari: # Nếu không chỉ định schema thì các truy vấn mặc định sẽ đi vào đây
      #      schema: ${DB_SCHEMA_HIKARI:schema_roomx}
      maximum-pool-size: 20   # Số lượng tối đa kết nối
      minimum-idle: 5         # Số lượng kết nối tối thiểu trong pool
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    baseline-on-migrate: true   # Chỉ tạo bảng từ jpa
    locations: classpath:db/migration/tenant
    schemas: public
    enabled: true
    placeholders:
      schema: ${FLYWAY_PLACEHOLDERS:public}


  #    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:roomx}
  #    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    properties: # Nếu hibernate không tìm thấy schema mặc định sẽ đi vào đây (cấp thấp hơn hikari)
      hibernate:
        #        generate_statistics: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: ${JPA_DDL_AUTO:none} # không bật trong production
      #      default_schema: ${DB_SCHEMA_HIBERNATE:DEFAULT}
      defer-datasource-initialization: true   # Ngăn insert dữ liệu trước khi jpa mapping
  jackson:
    serialization:
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true
  #  sql:
  #    init:
  #      mode: ${SQL_INIT_MODE:never}
  #      data-locations: ${SQL_INIT_DATA:classpath:database/data.sql}  # SQL native thêm dữ liệu
  #      schema-locations: ${SQL_INIT_SCHEMA:classpath:database/schema.sql} # SQL native tạo schema
  #  security:
  #    oauth2:
  #      resourceserver:
  #        jwt:
  #          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER:http://keycloak:5555/realms/roomx}
  #          jwk-set-uri: ${OAUTH2_RESOURCESERVER_JWT_JWK:http://keycloak:5555/realms/roomx/protocol/openid-connect/certs}
  mail:
    port: 587
    host: ${MAIL_HOST:smtp.gmail.com}
    username: ${MAIL_USERNAME:unknown@gmail.com}
    password: ${MAIL_PASSWORD:unknown}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${MAIL_DOMAIN_SSL:smtp.gmail.com}
  data:
    threads:
      virtual:
        enabled: true

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      connect-timeout: 30000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5
      redisson:
        pool:
          max-active: 100
          max-idle: 5
        retry:
          max-retry-attemps: ${REDIS_REDISSON_RETRY_MAX_RETRY_ATTEMPS:5} # 5 retries
          initial-delay: ${REDIS_REDISSON_RETRY_INITIAL_DELAY:1000}     # 1000 miliseconds
        circuitbreaker:
          failure-rate-threshold: ${REDIS_REDISSON_CIRCUIBREAKER_FAILURE_RATE_THRESHOLD:50}   # 50%
          wait-duration-in-open-state: ${REDIS_REDISSON_CIRCUIBREAKER_WAIT_DURATION_IN_OPEN_STATE:60}   # 60 seconds
          sliding-window-size: ${REDIS_REDISSON_CIRCUIBREAKER_SLIDING_WINDOW_SIZE:10}   # 10

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false




  kafka:
    bootstrap-servers: ${KAFKA_SERVER_URL:localhost:9092}
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: group-default
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        backoff.ms: ${KAFKA_PRODUCER_BACKOFF_MS:1000}    #  1000 miliseconds
        retries: ${KAFKA_PRODUCER_RETRIES:3}      #  3 retries
        delivery.timeout.ms: ${KAFKA_PRODUCER_DELIVERY_TIMEOUT_MS:120000}   # 2 minutes
        request.timeout.ms: ${KAFKA_PRODUCER_REQUEST_TIMEOUT_MS:30000}     # 30 seconds
        linger.ms: ${KAFKA_PRODUCER_LINGER_MS:5}       # 5 milliseconds
minio:
  url: ${MINIO_URL:http://localhost:9000}
  host-proxy: ${MINIO_HOST_PROXY:https://proxy.domain.com}
  domain: ${MINIO_DOMAIN:https://s3.domain.com}
  ssl: true
  access-key: ${MINIO_ACCESS_KEY:admin}
  secret-key: ${MINIO_SECRET_KEY:admin}
  bucket-policy-custom: '${MINIO_BUCKET_POLICY_CUSTOM:{ "Version": "2012-10-17", "Statement": [ { "Effect": "Allow", "Principal": "*", "Action": [ "s3:GetObject" ], "Resource": [ "arn:aws:s3:::%s/public/*" ] } ] }}'

resilience4j:
  ratelimiter:
    instances:
      test1:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      test2:
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
  circuitbreaker:
    instances:
      test3:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        #        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

      test4:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        #        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

keycloak:
  client-default: ${KEYCLOAK_CLIENT_DEFAULT:roomx-fe} # client mặc định cho app roomx
  realm: master
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:5555} # địa chỉ của keycloak server
  resource: ${KEYCLOAK_RESOURCE:roomx-backend-admin} # Client ID của ứng dụng liên lạc với backend
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET:NE5P98sS61cQ8bBBofe4kveX8rUEZ7Hy}
  use-resource-role-mappings: true
  bearer-only: true
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG

multitenancy:
  tenants:
    - identifier: ${MULTITENANCY_GIAU_IDENITIFIER:giau}
      enabled: ${MULTITENANCY_GIAU_ENABLED:true}
      schema: ${MULTITENANCY_GIAU_SCHEMA:giau}
      issuer: ${MULTITENANCY_GIAU_ISSUER:http://192.168.1.251:5555/realms/giau}
    - identifier: ${MULTITENANCY_SANG_IDENTIFIER:sang}
      enabled: ${MULTITENANCY_SANG_ENABLED:false}
      schema: ${MULTITENANCY_SANG_SCHEMA:sang}
      issuer: ${MULTITENANCY_SANG_ISSUER:http://192.168.1.251:5555/realms/sang}
#    - identifier: ${MULTITENANCY_HIEP_IDENTIFIER:hiep}
#      enabled: ${MULTITENANCY_HIEP_ENABLED:false}
#      schema: ${MULTITENANCY_HIEP_SCHEMA:hiep}
#      issuer: ${MULTITENANCY_HIEP_ISSUER:http://192.168.1.251:5555/realms/hiep}




###    FIREBASE
firebase:
  service-account: ${FIREBASE_SERVICE_ACCOUNT:}

### LOG

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
#  metrics:
#    tags:
#      application: ${spring.application.name}
#    distribution:
#      percentiles-histogram:
#        all: true
#        http.server.requests: true
#  opentelemetry:
#    resource-attributes:
#      application: ${spring.application.name}
#      "service.name": ${spring.application.name}
#  otlp:
#    tracing:
#      endpoint: ${MANAGEMANT_OLTP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
#  tracing:
#    sampling:
#      probability: 1.0
#  prometheus:
#    metrics:
#      export:
#        step: 5s



logging:
  level:
    #    org.springframework.transaction: DEBUG
    #    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.BasicBinder: TRACE
#  pattern:
#    correlation: '[%X{traceId:-}-%X{spanId:-}] [%X{tenantId:-}] '



