pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'roomx-be'
        DOCKER_TAG = 'latest'
//         DOCKER_USERNAME = credentials('docker-username')
//         DOCKER_PASSWORD = credentials('docker-password')
    }
/*
    // Stage build with docker
    stages {

        stage('Clone Repository') {
            steps {
                    git branch: 'dev-be', url: 'https://github.com/JiaG293/RoomX.git'
                }
        }

        stage('Build Docker Image') {
            steps {
                script {

                    // stop and delete container
                    sh 'docker rm -f $DOCKER_IMAGE || true'

                    // delete images older
                    sh 'docker rmi -f $DOCKER_IMAGE:$DOCKER_TAG || true'

                    // Build docker images
                    sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG RoomX-Backend/'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
//                     sh 'docker stop $DOCKER_IMAGE || true'
//                     sh 'docker rm $DOCKER_IMAGE || true'

                    // run docker container new
                    sh 'docker run --name $DOCKER_IMAGE -d -p 8888:8888 $DOCKER_IMAGE:$DOCKER_TAG'
                }
            }
        }

//          stage('Push Docker Image to Docker Hub') {
//             steps {
//                 script {
//                     sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
//                     sh 'docker push $DOCKER_IMAGE:$DOCKER_TAG'
//                 }
//             }
//         }
    }
*/

    //stage with docker compose
    stages {

            stage('Clone Repository') {
                steps {
                    git branch: 'dev-be', url: 'https://github.com/JiaG293/RoomX.git'
                }
            }

            stage('Load ENV File') {
                steps {
                    script {
                         withCredentials([file(credentialsId: 'roomx-be-dev-env', variable: 'ENV_FILE')]) {
                             sh '''
                                 set -x
                                 chmod 644 $ENV_FILE
                                 rm -f RoomX-Backend/.env || true
                                 cp $ENV_FILE RoomX-Backend/.env || true
                                 ls -la RoomX-Backend/
                             '''
                         }
                    }
                }
            }

            stage('Build Docker Image') {
                steps {
                    script {
                        // stop and remove container older
                        // build docker
                        sh '''
                            cd RoomX-Backend
                            docker compose down roomx-be || true
                            docker rmi -f roomx-backend-roomx-be:latest || true
                            docker compose build roomx-be
                        '''
                    }
                }
            }

            stage('Start/Restart Container/Update env') {
                steps {
                    script {
                        withCredentials([file(credentialsId: 'roomx-be-dev-env', variable: 'ENV_FILE')]) {
                            sh '''
                                chmod 644 $ENV_FILE
                                rm -f RoomX-Backend/.env || true
                                cp $ENV_FILE RoomX-Backend/.env || true

                                cd RoomX-Backend
                                docker compose up -d --force-recreate roomx-be || true                                                  docker compose up -d roomx-be
                            '''
                        }
                    }
                }
            }
    }


    post {
        always {
            cleanWs()
        }
    }
}